[project]
name = "hello_world_project"
version = "0.1.0"
description = "A basic Hello, World example app"
authors = [
    { name = "JsimmsDev", email = "example@example.com" }
]
license = { text = "Example" }
dependencies = []
